name: Ubuntu Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tarinyoom/grpc-conan:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/build

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build build --config Release
